# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-27 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('test_type', models.CharField(max_length=50)),
                ('test_status', models.CharField(max_length=50)),
                ('proj_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('browser', models.CharField(max_length=50)),
                ('build_info', models.CharField(max_length=200)),
                ('summary_desc', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sid'],
            },
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('message_content', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('task_desc', models.TextField()),
                ('test_result', models.CharField(blank=True, max_length=50, null=True)),
                ('task_created', models.DateTimeField(auto_now_add=True)),
                ('task_updated', models.DateTimeField(auto_now=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Summary')),
            ],
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Tasks'),
        ),
    ]
